### ISSUE TITLE
User login UX design

### ISSUE THREAD

**Issue by chenyair** [chenyair/tgmu#8]
**Is your feature request related to a problem? Please describe.**
In order to start developing I want to be able to know how the login flow would look like

**Describe the solution you'd like**
I want a design for the login flow

**Comment by liadyacobi** [comment]
# UI Design
## Overview
The UI design is simple yet eye catching with a photo of a movie catalog covering the most of the page to set the atmosphere for the user.
The login form is simple, providing all login methods in a simple UI and also a link for those who need to create a new account.

## Design
![Image](https://github.com/chenyair/tgmu/assets/65843947/d8ce4f0a-de5c-41bd-98e7-d973539c6088)

# UX Flow
### Overview
The User is presented with a few action buttons which allow different login methods and options
### Actions
1. Sign in with Google - When the user clicks this button it will open/navigate to a google login prompt
2. Email sign in - The user is able to use his email and password to login
3. Remember Me - Will keep the user logged into the system even when closing the tab
4. Log In - Attempts to log in with the given credentials
5. Create new account - If the user clicks on this button he will be navigated to the registration page, where he will be able to create his account which he will later use to login
